### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by StackXCore** [sjhloco/firewall_policy_report#1]
Hi,

I have tried run these command. but errors

root@computer:~$ python -m venv ~/venv/acl_report/
ource ~/venv/acl_report/bin/activate/usr/bin/python: No module named venv

root@computer:~$ source ~/venv/acl_report/bin/activate
-bash: /home/computer/venv/acl_report/bin/activate: No such file or directory

tried without above command. main.py show below errors
  File "main.py", line 92
    rc.print("The directory [i cyan]'{}'[/i cyan] does not exist, do you want to create it?".format(args['location']))
           ^
SyntaxError: invalid syntax

**Comment by sjhloco** [comment]
To be able to create a virtual environment (python -m venv ~/venv/acl_report/) you must have first installed the Python virtual environment package (pip install virtualenv). If using a virtual environment or not using a virtual environment you still have to first install all the python packages used by this script (pip install -r firewall_policy_report/requirements.txt), that is the reason you are getting a SyntaxError. As long as you install the packages the script should work, although I can't guarantees anything as I haven't used it for a while and is not something I actively support,

Thanks
